[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0001T"
key = "J"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 10
y = 5

[window.class]
general = "Alacritty"
instance = "Alacritty"

[general]
import = [
  # "~/.config/alacritty/tokio-night-dark.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/catppuccin-macchiato.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-latte.toml",
]
