import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
  # "~/.config/alacritty/tokio-night-dark.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-latte.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetbrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0001T"
key = "J"
mods = "Command"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 3
y = 2

[window.class]
general = "Alacritty"
instance = "Alacritty"
