
[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0001T"
key = "J"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

[general]
import = [
  # "~/.config/alacritty/tokio-night-dark.toml",
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/catppuccin-macchiato.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-latte.toml",
]
