theme = "onedark"

[editor]
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true
display-messages = true
