"$schema" = 'https://starship.rs/config-schema.json'

[fill]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[jobs]
symbol = " "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[package]
display_private = true
