require "core.utils.prequire"
require "plugins.configs.impatient"
require "core.options"
require "core.keymaps"
require "plugins"
require "core.colorscheme"
require "core.autocommands"
require "core.commands"
